# Generated by Django 5.2.15 on 2026-07-07 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0030_organizationsettings_realtime_candidates_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_store_id', models.CharField(max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'Created'),
                            ('receiving', 'Receiving'),
                            ('succeeded', 'Succeeded'),
                            ('failed', 'Failed'),
                            ('expired', 'Expired'),
                        ],
                        default='created',
                        max_length=40,
                    ),
                ),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('batches_applied', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_duplicate', models.PositiveIntegerField(default=0)),
                ('last_batch_seq', models.IntegerField(default=-1)),
                ('max_table_phase', models.IntegerField(default=-1)),
                ('applied_batches', models.JSONField(blank=True, default=dict)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('created_by_api_key', models.UUIDField(blank=True, null=True)),
                ('created_by_identity', models.UUIDField(blank=True, null=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.organization'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='core.project'
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='import_jobs',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', '-created_at'],
                'indexes': [
                    models.Index(fields=['organization', 'project', 'status'], name='imports_imp_organiz_472c89_idx'),
                    models.Index(fields=['organization', 'created_at'], name='imports_imp_organiz_db29f7_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('status__in', ('created', 'receiving'))),
                        fields=('organization', 'project', 'source_store_id'),
                        name='uniq_active_import_per_store',
                    )
                ],
            },
        ),
    ]
