# Generated by Django 5.2.15 on 2026-06-25 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0002_remove_outboxevent_core_outbox_unique_idempotency_key_per_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('built_in', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'identity_type',
                    models.CharField(
                        choices=[('user', 'User'), ('service_account', 'Service account')],
                        default='service_account',
                        max_length=40,
                    ),
                ),
                ('external_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='core.organization'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'identity_type', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_fingerprint', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='core.organization'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='api_keys',
                        to='core.project',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='api_keys',
                        to='core.team',
                    ),
                ),
                (
                    'owner_identity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='api_keys', to='access.identity'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'identity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='project_grants', to='access.identity'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_grants',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='core.project'
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='project_grants', to='access.role'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'identity_id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'identity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organization_memberships',
                        to='access.identity',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='organization_memberships',
                        to='core.organization',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='organization_memberships',
                        to='access.role',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'identity_id'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'capability',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='access.capability'
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='access.role'
                    ),
                ),
            ],
            options={
                'ordering': ['role_id', 'capability_id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                (
                    'identity',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_memberships',
                        to='access.identity',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team_memberships',
                        to='core.organization',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='access.role'
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.team'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'team_id', 'identity_id'],
            },
        ),
        migrations.CreateModel(
            name='ApiKeyCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'api_key',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='capability_links', to='access.apikey'
                    ),
                ),
                (
                    'capability',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='api_key_links',
                        to='access.capability',
                    ),
                ),
            ],
            options={
                'ordering': ['api_key_id', 'capability_id'],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('api_key', 'capability'), name='access_api_key_capability_unique_pair'
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name='identity',
            index=models.Index(
                fields=['organization', 'identity_type', 'active'], name='access_iden_organiz_049e4d_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='identity',
            constraint=models.UniqueConstraint(
                fields=('organization', 'identity_type', 'external_id'),
                name='access_identity_unique_external_id_per_org_type',
            ),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'key_prefix'], name='access_apik_organiz_5fb27c_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'project', 'active'], name='access_apik_organiz_5e0087_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['organization', 'owner_identity'], name='access_apik_organiz_c2f517_idx'),
        ),
        migrations.AddIndex(
            model_name='projectgrant',
            index=models.Index(fields=['organization', 'project', 'active'], name='access_proj_organiz_f9376f_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectgrant',
            constraint=models.UniqueConstraint(
                fields=('project', 'identity'), name='access_project_grant_unique_identity'
            ),
        ),
        migrations.AddIndex(
            model_name='organizationmembership',
            index=models.Index(fields=['organization', 'active'], name='access_orga_organiz_6d8e08_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(
                fields=('organization', 'identity'), name='access_org_membership_unique_identity'
            ),
        ),
        migrations.AddConstraint(
            model_name='rolecapability',
            constraint=models.UniqueConstraint(
                fields=('role', 'capability'), name='access_role_capability_unique_pair'
            ),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['organization', 'team', 'active'], name='access_team_organiz_d7d7d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(
                fields=('team', 'identity'), name='access_team_membership_unique_identity'
            ),
        ),
    ]
