# Generated by Django 5.2.15 on 2026-06-25 05:25

from django.db import migrations


CAPABILITIES = (
    ('members:*', 'Manage organization members.'),
    ('teams:*', 'Manage teams.'),
    ('projects:*', 'Manage and access projects.'),
    ('api_keys:*', 'Manage API keys.'),
    ('secrets:*', 'Manage provider secrets.'),
    ('model_policy:*', 'Manage model policy.'),
    ('observations:write', 'Submit observations.'),
    ('observations:read', 'Read observations.'),
    ('memories:read', 'Read approved memory.'),
    ('memories:propose', 'Propose memory updates.'),
    ('memories:review', 'Review memory proposals.'),
    ('memories:admin', 'Administer memory.'),
    ('search:query', 'Query memory search.'),
    ('audit:read', 'Read audit events.'),
    ('policy:admin', 'Administer policy.'),
)

ROLES = (
    ('organization_owner', 'Organization Owner', [code for code, _description in CAPABILITIES]),
    (
        'organization_admin',
        'Organization Admin',
        [
            'members:*',
            'teams:*',
            'projects:*',
            'api_keys:*',
            'secrets:*',
            'model_policy:*',
            'observations:write',
            'observations:read',
            'memories:read',
            'memories:propose',
            'memories:review',
            'memories:admin',
            'search:query',
            'audit:read',
            'policy:admin',
        ],
    ),
    (
        'developer',
        'Developer',
        [
            'observations:write',
            'observations:read',
            'memories:read',
            'memories:propose',
            'search:query',
        ],
    ),
    (
        'auditor',
        'Auditor',
        [
            'observations:read',
            'memories:read',
            'search:query',
            'audit:read',
        ],
    ),
)


def seed_default_roles(apps, schema_editor) -> None:
    capability_model = apps.get_model('access', 'Capability')
    role_model = apps.get_model('access', 'Role')
    role_capability_model = apps.get_model('access', 'RoleCapability')

    capabilities = {}
    for code, description in CAPABILITIES:
        capability, _created = capability_model.objects.update_or_create(
            code=code,
            defaults={'description': description},
        )
        capabilities[code] = capability

    for code, name, capability_codes in ROLES:
        role, _created = role_model.objects.update_or_create(
            code=code,
            defaults={'name': name, 'built_in': True},
        )
        for capability_code in capability_codes:
            role_capability_model.objects.get_or_create(
                role=role,
                capability=capabilities[capability_code],
            )


def unseed_default_roles(apps, schema_editor) -> None:
    capability_model = apps.get_model('access', 'Capability')
    role_model = apps.get_model('access', 'Role')
    role_capability_model = apps.get_model('access', 'RoleCapability')
    role_codes = [code for code, _name, _capabilities in ROLES]
    capability_codes = [code for code, _description in CAPABILITIES]

    role_capability_model.objects.filter(role__code__in=role_codes, capability__code__in=capability_codes).delete()
    role_model.objects.filter(code__in=role_codes).delete()
    capability_model.objects.filter(code__in=capability_codes).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_default_roles, unseed_default_roles),
    ]
