# Generated by Django 5.2.15 on 2026-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('access', '0005_seed_read_capabilities'),
        ('core', '0021_agentsession_model_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_prefix'], name='access_apik_key_pre_a1ebd1_idx'),
        ),
    ]
