# Generated by Django 5.2.15 on 2026-06-25 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'runtime',
                    models.CharField(
                        choices=[('claude_code', 'Claude Code'), ('codex', 'Codex'), ('unknown', 'Unknown')],
                        default='unknown',
                        max_length=40,
                    ),
                ),
                ('external_id', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['organization_id', 'runtime', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_session_id', models.CharField(max_length=255)),
                ('content_session_id', models.CharField(blank=True, max_length=255)),
                ('memory_session_id', models.CharField(blank=True, max_length=255)),
                (
                    'runtime',
                    models.CharField(
                        choices=[('claude_code', 'Claude Code'), ('codex', 'Codex'), ('unknown', 'Unknown')],
                        default='unknown',
                        max_length=40,
                    ),
                ),
                ('platform_source', models.CharField(blank=True, max_length=80)),
                ('repository_url', models.TextField(blank=True)),
                ('repository_root', models.TextField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('cwd', models.TextField(blank=True)),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('ended', 'Ended'), ('errored', 'Errored')],
                        default='active',
                        max_length=40,
                    ),
                ),
                ('prompt_counter', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='core.agent'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.organization'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'external_session_id'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('approved', 'Approved'),
                            ('archived', 'Archived'),
                            ('refuted', 'Refuted'),
                            ('conflict', 'Conflict'),
                        ],
                        default='approved',
                        max_length=40,
                    ),
                ),
                (
                    'visibility_scope',
                    models.CharField(
                        choices=[
                            ('session', 'Session'),
                            ('project', 'Project'),
                            ('team', 'Team'),
                            ('organization', 'Organization'),
                        ],
                        default='project',
                        max_length=40,
                    ),
                ),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('stale', models.BooleanField(default=False)),
                ('refuted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.organization'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'title'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.organization'
            ),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                ('repository_url', models.TextField(blank=True)),
                ('repository_root', models.TextField(blank=True)),
                ('default_branch', models.CharField(blank=True, max_length=255)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('facts', models.JSONField(blank=True, default=list)),
                ('narrative', models.TextField(blank=True)),
                ('concepts', models.JSONField(blank=True, default=list)),
                ('files_read', models.JSONField(blank=True, default=list)),
                ('files_modified', models.JSONField(blank=True, default=list)),
                ('prompt_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=128)),
                ('generation_key', models.CharField(blank=True, max_length=255)),
                ('generated_model', models.CharField(blank=True, max_length=120)),
                ('redaction_metadata', models.JSONField(blank=True, default=dict)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='core.agent'
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.agentsession'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.organization'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='core.project'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('content_hash', models.CharField(max_length=128)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                (
                    'memory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.memory'
                    ),
                ),
                (
                    'source_observation',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='memory_versions',
                        to='core.observation',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memory_versions',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memory_versions', to='core.project'
                    ),
                ),
            ],
            options={
                'ordering': ['memory_id', 'version'],
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='core.project'
            ),
        ),
        migrations.CreateModel(
            name='ContextBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.CharField(max_length=255)),
                ('purpose', models.CharField(max_length=80)),
                ('query_text', models.TextField(blank=True)),
                ('rendered_text', models.TextField(blank=True)),
                ('authorization_scope', models.JSONField(blank=True, default=dict)),
                ('token_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                (
                    'status',
                    models.CharField(
                        choices=[('created', 'Created'), ('injected', 'Injected'), ('skipped', 'Skipped')],
                        default='created',
                        max_length=40,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='context_bundles', to='core.agent'
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='context_bundles',
                        to='core.agentsession',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='context_bundles',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='context_bundles', to='core.project'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentsession',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.project'
            ),
        ),
        migrations.CreateModel(
            name='RawEventEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=120)),
                ('source_adapter', models.CharField(blank=True, max_length=80)),
                ('client_event_id', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=128)),
                (
                    'runtime',
                    models.CharField(
                        choices=[('claude_code', 'Claude Code'), ('codex', 'Codex'), ('unknown', 'Unknown')],
                        default='unknown',
                        max_length=40,
                    ),
                ),
                ('payload_schema_version', models.CharField(default='v1', max_length=40)),
                ('sequence_number', models.BigIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=255)),
                ('trace_id', models.CharField(blank=True, max_length=255)),
                ('actor_type', models.CharField(blank=True, max_length=80)),
                ('actor_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'agent',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='raw_events', to='core.agent'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='core.organization'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='core.project'
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='core.agentsession'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'received_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=255)),
                ('citation', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'observation',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.observation'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='observation_sources',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='observation_sources',
                        to='core.project',
                    ),
                ),
                (
                    'raw_event',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='observation_sources',
                        to='core.raweventenvelope',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'source_type', 'source_id'],
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='raw_event',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='observations',
                to='core.raweventenvelope',
            ),
        ),
        migrations.CreateModel(
            name='RetrievalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'visibility_scope',
                    models.CharField(
                        choices=[
                            ('session', 'Session'),
                            ('project', 'Project'),
                            ('team', 'Team'),
                            ('organization', 'Organization'),
                        ],
                        default='project',
                        max_length=40,
                    ),
                ),
                ('source_observation_ids', models.JSONField(blank=True, default=list)),
                ('file_paths', models.JSONField(blank=True, default=list)),
                ('symbols', models.JSONField(blank=True, default=list)),
                ('exact_terms', models.JSONField(blank=True, default=list)),
                ('full_text', models.TextField()),
                ('embedding_reference', models.CharField(blank=True, max_length=255)),
                ('stale', models.BooleanField(default=False)),
                ('refuted', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'memory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='retrieval_documents',
                        to='core.memory',
                    ),
                ),
                (
                    'memory_version',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='retrieval_document',
                        to='core.memoryversion',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='retrieval_documents',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='retrieval_documents',
                        to='core.project',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'memory_id'],
            },
        ),
        migrations.CreateModel(
            name='ContextBundleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.PositiveIntegerField()),
                ('citation', models.CharField(max_length=80)),
                ('inclusion_reason', models.TextField(blank=True)),
                ('scope_evidence', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'bundle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.contextbundle'
                    ),
                ),
                (
                    'memory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='context_bundle_items',
                        to='core.memory',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='context_bundle_items',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='context_bundle_items',
                        to='core.project',
                    ),
                ),
                (
                    'retrieval_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='context_bundle_items',
                        to='core.retrievaldocument',
                    ),
                ),
            ],
            options={
                'ordering': ['bundle_id', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=120)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.organization'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'slug'],
            },
        ),
        migrations.AddField(
            model_name='retrievaldocument',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='retrieval_documents',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='raweventenvelope',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='raw_events',
                to='core.team',
            ),
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='project_team_links',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='core.project'
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.team'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aggregate_type', models.CharField(max_length=120)),
                ('aggregate_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=120)),
                ('payload_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('actor_type', models.CharField(blank=True, max_length=80)),
                ('actor_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=255)),
                ('trace_id', models.CharField(blank=True, max_length=255)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('processing', 'Processing'),
                            ('done', 'Done'),
                            ('failed', 'Failed'),
                            ('dead_letter', 'Dead letter'),
                        ],
                        default='pending',
                        max_length=40,
                    ),
                ),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='outbox_events',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='outbox_events',
                        to='core.project',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='outbox_events',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['status', 'next_retry_at', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='observation',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='observations',
                to='core.team',
            ),
        ),
        migrations.CreateModel(
            name='MemoryCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                (
                    'status',
                    models.CharField(
                        choices=[('proposed', 'Proposed'), ('promoted', 'Promoted'), ('rejected', 'Rejected')],
                        default='proposed',
                        max_length=40,
                    ),
                ),
                (
                    'visibility_scope',
                    models.CharField(
                        choices=[
                            ('session', 'Session'),
                            ('project', 'Project'),
                            ('team', 'Team'),
                            ('organization', 'Organization'),
                        ],
                        default='project',
                        max_length=40,
                    ),
                ),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(max_length=128)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                (
                    'promoted_memory',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='source_candidates',
                        to='core.memory',
                    ),
                ),
                (
                    'source_observation',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='memory_candidates',
                        to='core.observation',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memory_candidates',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memory_candidates', to='core.project'
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='memory_candidates',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='memory',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memories',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='contextbundle',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='context_bundles',
                to='core.team',
            ),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=120)),
                ('actor_type', models.CharField(max_length=80)),
                ('actor_id', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('capability', models.CharField(blank=True, max_length=120)),
                (
                    'result',
                    models.CharField(
                        choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('recorded', 'Recorded')],
                        default='recorded',
                        max_length=40,
                    ),
                ),
                ('request_id', models.CharField(blank=True, max_length=255)),
                ('correlation_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='core.organization'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_events',
                        to='core.project',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='audit_events',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentsession',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sessions',
                to='core.team',
            ),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(
                fields=('organization', 'runtime', 'external_id'), name='core_agent_unique_external_id_per_runtime'
            ),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(
                fields=('organization', 'slug'), name='core_project_unique_slug_per_org'
            ),
        ),
        migrations.AddIndex(
            model_name='memoryversion',
            index=models.Index(
                fields=['organization', 'project', 'content_hash'], name='core_memory_organiz_64cdf1_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryversion',
            constraint=models.UniqueConstraint(fields=('memory', 'version'), name='core_memory_version_unique_version'),
        ),
        migrations.AddIndex(
            model_name='observationsource',
            index=models.Index(
                fields=['organization', 'project', 'source_type'], name='core_observ_organiz_9fb6a5_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='observationsource',
            constraint=models.UniqueConstraint(
                fields=('observation', 'source_type', 'source_id'), name='core_observation_source_unique_source'
            ),
        ),
        migrations.AddConstraint(
            model_name='contextbundleitem',
            constraint=models.UniqueConstraint(fields=('bundle', 'rank'), name='core_context_bundle_item_unique_rank'),
        ),
        migrations.AddConstraint(
            model_name='contextbundleitem',
            constraint=models.UniqueConstraint(
                fields=('bundle', 'memory'), name='core_context_bundle_item_unique_memory'
            ),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='core_team_unique_slug_per_org'),
        ),
        migrations.AddIndex(
            model_name='retrievaldocument',
            index=models.Index(
                fields=['organization', 'project', 'visibility_scope'], name='core_retrie_organiz_e7471d_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='retrievaldocument',
            index=models.Index(
                fields=['organization', 'project', 'stale', 'refuted'], name='core_retrie_organiz_e4ae24_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='raweventenvelope',
            index=models.Index(fields=['organization', 'project', 'event_type'], name='core_raweve_organiz_ac636f_idx'),
        ),
        migrations.AddIndex(
            model_name='raweventenvelope',
            index=models.Index(
                fields=['organization', 'project', 'content_hash'], name='core_raweve_organiz_2ca1a1_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='raweventenvelope',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'session', 'client_event_id'),
                name='core_raw_event_unique_client_event_per_session',
            ),
        ),
        migrations.AddConstraint(
            model_name='raweventenvelope',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'idempotency_key'),
                name='core_raw_event_unique_idempotency_key_per_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='projectteam',
            constraint=models.UniqueConstraint(fields=('project', 'team'), name='core_project_team_unique_pair'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='core_outbox_status_19e85a_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['organization', 'project', 'event_type'], name='core_outbox_organiz_1ae11b_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(
                fields=['organization', 'aggregate_type', 'aggregate_id'], name='core_outbox_organiz_f10286_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(
                fields=('organization', 'event_type', 'idempotency_key'),
                name='core_outbox_unique_idempotency_key_per_event',
            ),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(
                fields=['organization', 'project', 'observation_type'], name='core_observ_organiz_75bb32_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(
                fields=['organization', 'project', 'content_hash'], name='core_observ_organiz_7bdbfc_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'session', 'content_hash'),
                name='core_observation_unique_content_hash_per_session',
            ),
        ),
        migrations.AddIndex(
            model_name='memorycandidate',
            index=models.Index(fields=['organization', 'project', 'status'], name='core_memory_organiz_174138_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorycandidate',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'content_hash'),
                name='core_memory_candidate_unique_content_hash_per_project',
            ),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['organization', 'project', 'status'], name='core_memory_organiz_bc3fe1_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(
                fields=['organization', 'project', 'visibility_scope'], name='core_memory_organiz_6de68a_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='contextbundle',
            index=models.Index(fields=['organization', 'project', 'purpose'], name='core_contex_organiz_e5c264_idx'),
        ),
        migrations.AddConstraint(
            model_name='contextbundle',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'request_id'), name='core_context_bundle_unique_request_per_project'
            ),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'project', 'event_type'], name='core_audite_organiz_11898b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'result'], name='core_audite_organiz_303e98_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['organization', 'project', 'status'], name='core_agents_organiz_11e847_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'external_session_id'),
                name='core_session_unique_external_id_per_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.UniqueConstraint(
                condition=models.Q(('content_session_id', ''), _negated=True),
                fields=('organization', 'project', 'content_session_id'),
                name='core_session_unique_content_id_per_project',
            ),
        ),
    ]
