# Generated by Django 5.2.15 on 2026-06-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='outboxevent',
            name='core_outbox_unique_idempotency_key_per_event',
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='source_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='source_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(
                fields=('organization', 'event_type', 'source_type', 'source_id', 'idempotency_key'),
                name='core_outbox_unique_idempotency_key_per_event',
            ),
        ),
    ]
