# Generated by Django 5.2.15 on 2026-06-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_delete_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrievaldocument',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
