# Generated by Django 5.2.15 on 2026-06-26 01:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_retrievaldocument_embedding_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'link_type',
                    models.CharField(
                        choices=[('file', 'File'), ('symbol', 'Symbol'), ('commit', 'Commit'), ('issue', 'Issue')],
                        max_length=40,
                    ),
                ),
                ('target', models.CharField(max_length=1024)),
                ('label', models.CharField(blank=True, max_length=255)),
                (
                    'memory',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.memory'
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memory_links', to='core.organization'
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='memory_links', to='core.project'
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'memory_id', 'link_type', 'target'],
                'indexes': [
                    models.Index(fields=['organization', 'project', 'link_type'], name='core_memory_organiz_476fdd_idx')
                ],
                'constraints': [
                    models.UniqueConstraint(
                        fields=('memory', 'link_type', 'target'), name='core_memory_link_unique_target'
                    )
                ],
            },
        ),
    ]
