# Generated by Django 5.2.15 on 2026-06-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_organization_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(
                choices=[
                    ('active', 'Active'),
                    ('trialing', 'Trialing'),
                    ('past_due', 'Past due'),
                    ('suspended', 'Suspended'),
                    ('pending_delete', 'Pending delete'),
                ],
                default='active',
                max_length=20,
            ),
        ),
    ]
