# Generated by Django 5.2.15 on 2026-06-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0012_organization_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='distillation_auto_approve_threshold',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='run_type',
            field=models.CharField(
                choices=[
                    ('daily_digest', 'Daily Digest'),
                    ('observation_processing', 'Observation Processing'),
                    ('session_distillation', 'Session Distillation'),
                ],
                max_length=40,
            ),
        ),
    ]
