# Generated by Django 5.2.15 on 2026-06-30 10:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_alter_workflowrun_run_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='curator_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='near_dup_threshold',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.850'), max_digits=4),
        ),
    ]
