# Generated by Django 5.2.15 on 2026-06-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_organizationsettings_curator_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='curator_llm_judge_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
