# Generated by Django 5.2.15 on 2026-06-30 21:24

from django.db import migrations, models


def backfill_memory_kind_from_metadata(apps: object, schema_editor: object) -> None:
    Memory = apps.get_model('core', 'Memory')
    for memory in Memory.objects.only('id', 'metadata', 'kind').iterator():
        kind = memory.metadata.get('kind')
        if kind and memory.kind != kind:
            memory.kind = kind
            memory.save(update_fields=['kind'])


def noop_reverse(apps: object, schema_editor: object) -> None:
    return


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_organizationsettings_lexical_recall_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.RunPython(backfill_memory_kind_from_metadata, noop_reverse),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['organization', 'project', 'updated_at'], name='core_session_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'created_at'], name='core_audit_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'project', 'created_at'], name='core_audit_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contextbundle',
            index=models.Index(fields=['organization', 'project', 'created_at'], name='core_ctxbundle_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(
                fields=['organization', 'project', 'status', 'updated_at'], name='core_memory_status_updated_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['organization', 'project', 'created_at'], name='core_memory_created_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['organization', 'project', 'kind'], name='core_memory_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(
                fields=['organization', 'project', 'observed_at', 'created_at'], name='core_observation_created_idx'
            ),
        ),
    ]
