# Generated by Django 5.2.15 on 2026-06-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_memory_kind_agentsession_core_session_updated_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='model_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
