# Generated by Django 5.2.15 on 2026-07-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_agentsession_model_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextbundle',
            name='retrieval_latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
