# Generated by Django 5.2.15 on 2026-07-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_alter_auditevent_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorylink',
            name='link_type',
            field=models.CharField(
                choices=[
                    ('file', 'File'),
                    ('symbol', 'Symbol'),
                    ('commit', 'Commit'),
                    ('issue', 'Issue'),
                    ('narrowed_by', 'Narrowed by'),
                    ('superseded_by', 'Superseded by'),
                    ('conflicts_with', 'Conflicts With'),
                ],
                max_length=40,
            ),
        ),
    ]
