# Generated by Django 5.2.15 on 2026-07-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_alter_memorylink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorycandidate',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
