# Generated by Django 5.2.15 on 2026-07-04 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_memorycandidate_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='confidence_decay_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
