# Generated by Django 5.2.15 on 2026-07-04 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0028_organizationsettings_confidence_decay_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryReviewExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(max_length=40)),
                ('item_id', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=40)),
                ('snapshot', models.JSONField(default=dict)),
                ('curator_context', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('actor_id', models.CharField(blank=True, max_length=255)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memory_review_examples',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memory_review_examples',
                        to='core.project',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='memory_review_examples',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', '-created_at'],
                'indexes': [
                    models.Index(
                        fields=['organization', 'project', 'created_at'], name='core_memory_organiz_9e4f98_idx'
                    ),
                    models.Index(fields=['organization', 'action'], name='core_memory_organiz_4f46b4_idx'),
                ],
            },
        ),
    ]
