# Generated by Django 5.2.16 on 2026-07-10 10:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0031_workflowrun_active_daily_digest_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'work_type',
                    models.CharField(
                        choices=[
                            ('observation_processing', 'Observation Processing'),
                            ('session_distillation', 'Session Distillation'),
                            ('daily_digest', 'Daily Digest'),
                            ('weekly_digest', 'Weekly Digest'),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    'subject_type',
                    models.CharField(
                        choices=[
                            ('observation', 'Observation'),
                            ('agent_session', 'Agent Session'),
                            ('project', 'Project'),
                            ('team', 'Team'),
                        ],
                        max_length=40,
                    ),
                ),
                ('subject_id', models.UUIDField()),
                ('contract_version', models.PositiveSmallIntegerField(default=1)),
                ('occurrence_key', models.CharField(blank=True, max_length=255)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('input_snapshot', models.JSONField()),
                (
                    'disposition',
                    models.CharField(
                        choices=[('required', 'Required'), ('complete', 'Complete'), ('no_op', 'No-op')],
                        default='required',
                        max_length=20,
                    ),
                ),
                (
                    'resolution_reason',
                    models.CharField(
                        blank=True,
                        choices=[('succeeded', 'Succeeded'), ('no_signal', 'No signal'), ('no_input', 'No input')],
                        max_length=40,
                    ),
                ),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agentsession',
            name='end_work_contract_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='observation_sequence_cursor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='session_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raweventenvelope',
            name='normalization_contract_version',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raweventenvelope',
            name='normalization_disposition',
            field=models.CharField(
                blank=True, choices=[('observation', 'Observation'), ('no_op', 'No-op')], max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name='raweventenvelope',
            name='normalization_reason',
            field=models.CharField(blank=True, choices=[('evidence_only', 'Evidence only')], max_length=40, null=True),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(
                fields=['organization', 'project', 'status', 'end_work_contract_version'],
                name='core_session_end_work_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(
                fields=['organization', 'project', 'session', 'session_sequence'], name='core_obs_scope_session_seq_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='raweventenvelope',
            index=models.Index(
                fields=['organization', 'project', 'normalization_contract_version', 'normalization_disposition'],
                name='core_raw_norm_disposition_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='agentsession',
            constraint=models.CheckConstraint(
                condition=models.Q(('end_work_contract_version__in', (0, 1))), name='core_session_end_contract_ck'
            ),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(
                condition=models.Q(('session_sequence__isnull', False)),
                fields=('session', 'session_sequence'),
                name='core_obs_session_seq_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(
                condition=models.Q(('session_sequence__isnull', True), ('session_sequence__gt', 0), _connector='OR'),
                name='core_obs_session_seq_pos',
            ),
        ),
        migrations.AddConstraint(
            model_name='raweventenvelope',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('normalization_contract_version__isnull', True),
                        ('normalization_disposition__isnull', True),
                        ('normalization_reason__isnull', True),
                    ),
                    models.Q(
                        ('normalization_contract_version', 1),
                        ('normalization_contract_version__isnull', False),
                        ('normalization_disposition', 'observation'),
                        ('normalization_disposition__isnull', False),
                        ('normalization_reason__isnull', True),
                    ),
                    models.Q(
                        ('normalization_contract_version', 1),
                        ('normalization_contract_version__isnull', False),
                        ('normalization_disposition', 'no_op'),
                        ('normalization_disposition__isnull', False),
                        ('normalization_reason', 'evidence_only'),
                        ('normalization_reason__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='core_raw_norm_expand_valid',
            ),
        ),
        migrations.AddField(
            model_name='workflowwork',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='workflow_works', to='core.organization'
            ),
        ),
        migrations.AddField(
            model_name='workflowwork',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='workflow_works', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='workflowwork',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='workflow_works',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='work',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='attempts',
                to='core.workflowwork',
            ),
        ),
        migrations.AddIndex(
            model_name='workflowwork',
            index=models.Index(fields=['organization', 'project', 'disposition'], name='core_work_scope_disp_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowwork',
            index=models.Index(
                fields=['organization', 'project', 'work_type', 'disposition'], name='core_work_type_disp_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='workflowwork',
            index=models.Index(
                fields=['organization', 'project', 'subject_type', 'subject_id'], name='core_work_subject_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='workflowwork',
            index=models.Index(
                fields=['organization', 'project', 'work_type', 'occurrence_key'], name='core_work_occurrence_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.UniqueConstraint(
                fields=(
                    'organization',
                    'project',
                    'work_type',
                    'subject_type',
                    'subject_id',
                    'contract_version',
                    'input_fingerprint',
                ),
                name='core_work_identity_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.UniqueConstraint(
                condition=models.Q(('occurrence_key', ''), _negated=True),
                fields=(
                    'organization',
                    'project',
                    'work_type',
                    'subject_type',
                    'subject_id',
                    'contract_version',
                    'occurrence_key',
                ),
                name='core_work_occurrence_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(('contract_version__gt', 0)), name='core_work_contract_ver_pos'
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(('input_fingerprint__regex', '^[0-9a-f]{64}$')), name='core_work_fingerprint_hex'
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('occurrence_key', ''), ('subject_type', 'observation'), ('work_type', 'observation_processing')
                    ),
                    models.Q(
                        ('occurrence_key', ''), ('subject_type', 'agent_session'), ('work_type', 'session_distillation')
                    ),
                    models.Q(
                        ('subject_id', models.F('project_id')),
                        ('subject_type', 'project'),
                        ('team__isnull', True),
                        ('work_type', 'daily_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('subject_id', models.F('project_id')),
                        ('subject_type', 'project'),
                        ('team__isnull', True),
                        ('work_type', 'weekly_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('subject_id', models.F('team_id')),
                        ('subject_type', 'team'),
                        ('team__isnull', False),
                        ('work_type', 'weekly_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    _connector='OR',
                ),
                name='core_work_subject_scope_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('disposition', 'required'), ('resolution_reason', ''), ('resolved_at__isnull', True)),
                    models.Q(
                        ('disposition', 'complete'),
                        ('resolution_reason__in', ('succeeded', 'no_signal')),
                        ('resolved_at__isnull', False),
                    ),
                    models.Q(
                        ('disposition', 'no_op'), ('resolution_reason', 'no_input'), ('resolved_at__isnull', False)
                    ),
                    _connector='OR',
                ),
                name='core_work_terminal_state_ck',
            ),
        ),
    ]
