# Generated by Django 5.2.16 on 2026-07-13 17:04

import uuid

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

_DISTILLATION_LEDGER_MODELS = (
    'DistillationWindow',
    'DistillationChunk',
    'DistillationStage',
    'DistillationObservationCoverage',
    'MemoryCandidateSource',
)


def _guard_reverse(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    alias = schema_editor.connection.alias

    for model_name in _DISTILLATION_LEDGER_MODELS:
        if apps.get_model('core', model_name).objects.using(alias).exists():
            raise RuntimeError(f'cannot reverse 0036 while distillation ledger {model_name} exists')

    candidate_model = apps.get_model('core', 'MemoryCandidate')
    if candidate_model.objects.using(alias).exclude(decision_work_contract_version=0).exists():
        raise RuntimeError('cannot reverse 0036 while distillation candidate decision contract is activated')

    work_model = apps.get_model('core', 'WorkflowWork')
    if (
        work_model.objects.using(alias)
        .filter(models.Q(work_type='candidate_decision') | models.Q(subject_type='memory_candidate'))
        .exists()
    ):
        raise RuntimeError('cannot reverse 0036 while distillation candidate-decision work exists')

    run_model = apps.get_model('core', 'WorkflowRun')
    if run_model.objects.using(alias).filter(run_type='candidate_decision').exists():
        raise RuntimeError('cannot reverse 0036 while distillation candidate-decision run exists')

    return


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0035_workflow_work_execution'),
        ('model_policy', '0004_alter_providercallrecord_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistillationChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('first_sequence', models.PositiveBigIntegerField()),
                ('last_sequence', models.PositiveBigIntegerField()),
                ('observation_count', models.PositiveIntegerField()),
                ('input_manifest', models.JSONField()),
                ('input_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['window_id', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='DistillationObservationCoverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_sequence', models.PositiveBigIntegerField()),
                ('observation_digest', models.CharField(max_length=64)),
                (
                    'outcome',
                    models.CharField(choices=[('signal', 'Signal'), ('no_signal', 'No signal')], max_length=16),
                ),
            ],
            options={
                'ordering': ['window_id', 'session_sequence'],
            },
        ),
        migrations.CreateModel(
            name='DistillationStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_kind', models.CharField(choices=[('extract', 'Extract'), ('reduce', 'Reduce')], max_length=16)),
                ('level', models.PositiveSmallIntegerField()),
                ('ordinal', models.PositiveIntegerField()),
                ('target_key', models.CharField(max_length=64)),
                ('stage_key', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
                ('input_manifest', models.JSONField()),
                ('prompt_contract', models.CharField(max_length=80)),
                ('policy_version', models.PositiveIntegerField()),
                (
                    'policy_role',
                    models.CharField(choices=[('primary', 'Primary'), ('fallback', 'Fallback')], max_length=16),
                ),
                (
                    'status',
                    models.CharField(choices=[('required', 'Required'), ('complete', 'Complete')], max_length=16),
                ),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_failure_class', models.CharField(blank=True, default='', max_length=80)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('response_hash', models.CharField(blank=True, default='', max_length=64)),
                ('response_size', models.PositiveIntegerField(blank=True, null=True)),
                ('output_snapshot', models.JSONField(blank=True, null=True)),
                ('output_hash', models.CharField(blank=True, default='', max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['window_id', 'stage_kind', 'level', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='DistillationWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_version', models.PositiveSmallIntegerField()),
                ('lower_sequence_exclusive', models.PositiveBigIntegerField()),
                ('upper_sequence_inclusive', models.PositiveBigIntegerField()),
                ('observation_count', models.PositiveIntegerField()),
                ('input_hash', models.CharField(max_length=64)),
                ('chunk_char_budget', models.PositiveIntegerField()),
                ('reduction_target', models.PositiveIntegerField()),
                ('chunk_contract_version', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryCandidateSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchors', models.JSONField()),
                ('anchors_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['candidate_id', 'window_id', 'observation_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='workflowwork',
            name='core_work_subject_scope_ck',
        ),
        migrations.AddField(
            model_name='memorycandidate',
            name='decision_work_contract_version',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='run_type',
            field=models.CharField(
                choices=[
                    ('daily_digest', 'Daily Digest'),
                    ('observation_processing', 'Observation Processing'),
                    ('session_distillation', 'Session Distillation'),
                    ('weekly_digest', 'Weekly Digest'),
                    ('candidate_decision', 'Candidate Decision'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='workflowwork',
            name='subject_type',
            field=models.CharField(
                choices=[
                    ('observation', 'Observation'),
                    ('agent_session', 'Agent Session'),
                    ('project', 'Project'),
                    ('team', 'Team'),
                    ('memory_candidate', 'Memory Candidate'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='workflowwork',
            name='work_type',
            field=models.CharField(
                choices=[
                    ('observation_processing', 'Observation Processing'),
                    ('session_distillation', 'Session Distillation'),
                    ('daily_digest', 'Daily Digest'),
                    ('weekly_digest', 'Weekly Digest'),
                    ('candidate_decision', 'Candidate Decision'),
                ],
                max_length=40,
            ),
        ),
        migrations.AddIndex(
            model_name='memorycandidate',
            index=models.Index(
                fields=['organization', 'project', 'status', 'decision_work_contract_version'],
                name='core_cand_decision_ver_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='memorycandidate',
            constraint=models.CheckConstraint(
                condition=models.Q(('decision_work_contract_version__in', (0, 1))),
                name='core_memory_candidate_decision_ver_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('occurrence_key', ''), ('subject_type', 'observation'), ('work_type', 'observation_processing')
                    ),
                    models.Q(
                        ('occurrence_key', ''), ('subject_type', 'agent_session'), ('work_type', 'session_distillation')
                    ),
                    models.Q(
                        ('subject_id', models.F('project_id')),
                        ('subject_type', 'project'),
                        ('team__isnull', True),
                        ('work_type', 'daily_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('subject_id', models.F('project_id')),
                        ('subject_type', 'project'),
                        ('team__isnull', True),
                        ('work_type', 'weekly_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('subject_id', models.F('team_id')),
                        ('subject_type', 'team'),
                        ('team__isnull', False),
                        ('work_type', 'weekly_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('occurrence_key', ''),
                        ('subject_type', 'memory_candidate'),
                        ('work_type', 'candidate_decision'),
                    ),
                    _connector='OR',
                ),
                name='core_work_subject_scope_ck',
            ),
        ),
        migrations.AddField(
            model_name='distillationchunk',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_chunks', to='core.organization'
            ),
        ),
        migrations.AddField(
            model_name='distillationchunk',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_chunks', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='distillationchunk',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distillation_chunks',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='distillationobservationcoverage',
            name='observation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distillation_coverages',
                to='core.observation',
            ),
        ),
        migrations.AddField(
            model_name='distillationobservationcoverage',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='distillation_coverages',
                to='core.organization',
            ),
        ),
        migrations.AddField(
            model_name='distillationobservationcoverage',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_coverages', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='distillationobservationcoverage',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distillation_coverages',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='accepted_provider_call',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accepted_distillation_stage',
                to='model_policy.providercallrecord',
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='chunk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stages',
                to='core.distillationchunk',
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_stages', to='core.organization'
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='policy',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distillation_stages',
                to='model_policy.modelpolicy',
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_stages', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distillation_stages',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='distillationobservationcoverage',
            name='deciding_stage',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='core.distillationstage'
            ),
        ),
        migrations.AddField(
            model_name='distillationwindow',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_windows', to='core.organization'
            ),
        ),
        migrations.AddField(
            model_name='distillationwindow',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='distillation_windows', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='distillationwindow',
            name='session',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='distillation_windows', to='core.agentsession'
            ),
        ),
        migrations.AddField(
            model_name='distillationwindow',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='distillation_windows',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='distillationwindow',
            name='work',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name='distillation_window', to='core.workflowwork'
            ),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='window',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='core.distillationwindow'
            ),
        ),
        migrations.AddField(
            model_name='distillationobservationcoverage',
            name='window',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='coverages', to='core.distillationwindow'
            ),
        ),
        migrations.AddField(
            model_name='distillationchunk',
            name='window',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='core.distillationwindow'
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='candidate',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='core.memorycandidate'
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='observation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='candidate_sources', to='core.observation'
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='memory_candidate_sources',
                to='core.organization',
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='memory_candidate_sources', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='stage',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='candidate_sources',
                to='core.distillationstage',
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_candidate_sources',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='memorycandidatesource',
            name='window',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='candidate_sources',
                to='core.distillationwindow',
            ),
        ),
        migrations.AddIndex(
            model_name='distillationwindow',
            index=models.Index(
                fields=['organization', 'project', 'session', 'upper_sequence_inclusive'],
                name='core_distill_window_scope_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'session', 'input_hash'), name='core_distill_window_scope_hash_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('lower_sequence_exclusive__gte', 0),
                    ('upper_sequence_inclusive__gt', models.F('lower_sequence_exclusive')),
                ),
                name='core_distill_window_bounds_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(('observation_count__gt', 0)), name='core_distill_window_obs_count_pos'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(('chunk_char_budget__gt', 0)), name='core_distill_window_budget_pos'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(('reduction_target__gt', 0)), name='core_distill_window_reduction_target_pos'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(('input_hash__regex', '^[0-9a-f]{64}$')), name='core_distill_window_input_hash_hex'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(('contract_version', 1)), name='core_distill_window_contract_ck'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationwindow',
            constraint=models.CheckConstraint(
                condition=models.Q(('chunk_contract_version', 1)), name='core_distill_window_chunk_contract_ck'
            ),
        ),
        migrations.AddIndex(
            model_name='distillationstage',
            index=models.Index(
                fields=['organization', 'project', 'window', 'stage_kind', 'status'],
                name='core_distill_stage_scope_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'stage_key'), name='core_distill_stage_key_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.UniqueConstraint(
                fields=('window', 'stage_kind', 'level', 'ordinal', 'policy', 'policy_version'),
                name='core_distill_stage_coord_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status', 'complete')),
                fields=('window', 'target_key'),
                name='core_distill_stage_target_complete_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('stage_kind', 'extract'), _negated=True),
                    models.Q(('chunk__isnull', False), ('level', 0)),
                    _connector='OR',
                ),
                name='core_distill_stage_extract_shape_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('stage_kind', 'reduce'), _negated=True),
                    models.Q(('chunk__isnull', True), ('level__gt', 0)),
                    _connector='OR',
                ),
                name='core_distill_stage_reduce_shape_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('accepted_provider_call__isnull', True),
                        ('completed_at__isnull', True),
                        ('output_hash', ''),
                        ('output_snapshot__isnull', True),
                        ('response_hash', ''),
                        ('response_size__isnull', True),
                        ('status', 'required'),
                    ),
                    models.Q(
                        ('accepted_provider_call__isnull', False),
                        ('completed_at__isnull', False),
                        ('output_hash__regex', '^[0-9a-f]{64}$'),
                        ('output_snapshot__isnull', False),
                        ('response_hash__regex', '^[0-9a-f]{64}$'),
                        ('response_size__gt', 0),
                        ('status', 'complete'),
                    ),
                    _connector='OR',
                ),
                name='core_distill_stage_status_shape_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(('policy_version__gt', 0)), name='core_distill_stage_policy_version_pos'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(('target_key__regex', '^[0-9a-f]{64}$')), name='core_distill_stage_target_key_hex'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(('stage_key__regex', '^[0-9a-f]{64}$')), name='core_distill_stage_stage_key_hex'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationstage',
            constraint=models.CheckConstraint(
                condition=models.Q(('input_hash__regex', '^[0-9a-f]{64}$')), name='core_distill_stage_input_hash_hex'
            ),
        ),
        migrations.AddIndex(
            model_name='distillationobservationcoverage',
            index=models.Index(fields=['organization', 'project', 'window'], name='core_distill_cov_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='distillationobservationcoverage',
            constraint=models.UniqueConstraint(
                fields=('window', 'observation'), name='core_distill_coverage_window_obs_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationobservationcoverage',
            constraint=models.UniqueConstraint(
                fields=('window', 'session_sequence'), name='core_distill_coverage_window_seq_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationobservationcoverage',
            constraint=models.CheckConstraint(
                condition=models.Q(('observation_digest__regex', '^[0-9a-f]{64}$')),
                name='core_distill_coverage_digest_hex',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationobservationcoverage',
            constraint=models.CheckConstraint(
                condition=models.Q(('session_sequence__gt', 0)), name='core_distill_coverage_seq_pos'
            ),
        ),
        migrations.AddIndex(
            model_name='distillationchunk',
            index=models.Index(
                fields=['organization', 'project', 'window', 'ordinal'], name='core_distill_chunk_scope_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationchunk',
            constraint=models.UniqueConstraint(
                fields=('window', 'ordinal'), name='core_distill_chunk_window_ordinal_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationchunk',
            constraint=models.UniqueConstraint(
                fields=('window', 'input_hash'), name='core_distill_chunk_window_hash_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationchunk',
            constraint=models.CheckConstraint(
                condition=models.Q(('first_sequence__gt', 0), ('last_sequence__gte', models.F('first_sequence'))),
                name='core_distill_chunk_sequence_bounds_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationchunk',
            constraint=models.CheckConstraint(
                condition=models.Q(('observation_count__gt', 0)), name='core_distill_chunk_obs_count_pos'
            ),
        ),
        migrations.AddConstraint(
            model_name='distillationchunk',
            constraint=models.CheckConstraint(
                condition=models.Q(('input_hash__regex', '^[0-9a-f]{64}$')), name='core_distill_chunk_input_hash_hex'
            ),
        ),
        migrations.AddIndex(
            model_name='memorycandidatesource',
            index=models.Index(fields=['organization', 'project', 'candidate'], name='core_cand_source_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='memorycandidatesource',
            index=models.Index(fields=['window', 'observation'], name='core_cand_source_winobs_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorycandidatesource',
            constraint=models.UniqueConstraint(
                fields=('candidate', 'window', 'observation'), name='core_candidate_source_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='memorycandidatesource',
            constraint=models.CheckConstraint(
                condition=models.Q(('anchors_hash__regex', '^[0-9a-f]{64}$')), name='core_candidate_source_anchors_hex'
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, _guard_reverse),
    ]
