# Generated by Django 5.2.16 on 2026-07-14 21:43

import uuid

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def _allow_forward(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    return None


def _guard_reverse(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    transition_model = apps.get_model('core', 'MemoryTransition')
    if transition_model.objects.exists():
        raise RuntimeError('cannot reverse 0038 while MemoryTransition history exists')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0037_distillation_stage_policy_role_coord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_hash', models.CharField(max_length=64)),
                (
                    'resolution',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('publish_candidate', 'Publish candidate'),
                            ('merge_candidate', 'Merge candidate'),
                            ('supersede_memory', 'Supersede memory'),
                            ('reject_candidate', 'Reject candidate'),
                        ],
                        default='',
                        max_length=40,
                    ),
                ),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'transition_type',
                    models.CharField(
                        choices=[
                            ('promote', 'Promote'),
                            ('publish_digest', 'Publish digest'),
                            ('revise', 'Revise'),
                            ('attach_source', 'Attach source'),
                            ('merge', 'Merge'),
                            ('supersede', 'Supersede'),
                            ('mark_stale', 'Mark stale'),
                            ('refute', 'Refute'),
                            ('restore', 'Restore'),
                            ('archive', 'Archive'),
                            ('conflict_open', 'Open conflict'),
                            ('conflict_resolve', 'Resolve conflict'),
                        ],
                        max_length=40,
                    ),
                ),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('provenance_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryVersionSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_content_hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['memory_version_id', 'created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='workflowwork',
            name='core_work_subject_scope_ck',
        ),
        migrations.RemoveConstraint(
            model_name='workflowwork',
            name='core_work_terminal_state_ck',
        ),
        migrations.AddField(
            model_name='memory',
            name='transition_contract_version',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='retrievaldocument',
            name='embedding_projected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retrievaldocument',
            name='embedding_projection_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='retrievaldocument',
            name='exact_projection_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='retrievaldocument',
            name='projection_contract_version',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='origin',
            field=models.CharField(
                choices=[
                    ('legacy', 'Legacy'),
                    ('automatic', 'Automatic'),
                    ('reconciliation', 'Reconciliation'),
                    ('manual', 'Manual'),
                    ('memory_transition', 'Memory Transition'),
                ],
                db_default='legacy',
                default='legacy',
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='run_type',
            field=models.CharField(
                choices=[
                    ('daily_digest', 'Daily Digest'),
                    ('observation_processing', 'Observation Processing'),
                    ('session_distillation', 'Session Distillation'),
                    ('weekly_digest', 'Weekly Digest'),
                    ('candidate_decision', 'Candidate Decision'),
                    ('memory_embedding', 'Memory Embedding'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='workflowwork',
            name='subject_type',
            field=models.CharField(
                choices=[
                    ('observation', 'Observation'),
                    ('agent_session', 'Agent Session'),
                    ('project', 'Project'),
                    ('team', 'Team'),
                    ('memory_candidate', 'Memory Candidate'),
                    ('retrieval_document', 'Retrieval Document'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='workflowwork',
            name='resolution_reason',
            field=models.CharField(
                blank=True,
                choices=[
                    ('succeeded', 'Succeeded'),
                    ('no_signal', 'No signal'),
                    ('projection_superseded', 'Projection superseded'),
                    ('no_input', 'No input'),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name='workflowwork',
            name='work_type',
            field=models.CharField(
                choices=[
                    ('observation_processing', 'Observation Processing'),
                    ('session_distillation', 'Session Distillation'),
                    ('daily_digest', 'Daily Digest'),
                    ('weekly_digest', 'Weekly Digest'),
                    ('candidate_decision', 'Candidate Decision'),
                    ('memory_embedding', 'Memory Embedding'),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name='retrievaldocument',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('projection_contract_version', 0),
                    models.Q(('exact_projection_hash__regex', '^[0-9a-f]{64}$'), ('projection_contract_version', 1)),
                    _connector='OR',
                ),
                name='core_retrieval_document_projection_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='retrievaldocument',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('projection_contract_version', 0),
                    models.Q(
                        ('projection_contract_version', 1),
                        models.Q(
                            models.Q(
                                ('embedding_projected_at__isnull', True),
                                ('embedding_projection_hash', ''),
                                ('embedding_reference', ''),
                                ('embedding_vector', []),
                                ('embedding_pgvector__isnull', True),
                            ),
                            models.Q(
                                ('embedding_projected_at__isnull', False),
                                ('embedding_projection_hash', models.F('exact_projection_hash')),
                                ('embedding_projection_hash__regex', '^[0-9a-f]{64}$'),
                                ('embedding_reference__gt', ''),
                                models.Q(('embedding_vector', []), _negated=True),
                                ('embedding_pgvector__isnull', False),
                            ),
                            _connector='OR',
                        ),
                    ),
                    _connector='OR',
                ),
                name='core_retrieval_document_embedding_state_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('occurrence_key', ''), ('subject_type', 'observation'), ('work_type', 'observation_processing')
                    ),
                    models.Q(
                        ('occurrence_key', ''), ('subject_type', 'agent_session'), ('work_type', 'session_distillation')
                    ),
                    models.Q(
                        ('subject_id', models.F('project_id')),
                        ('subject_type', 'project'),
                        ('team__isnull', True),
                        ('work_type', 'daily_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('subject_id', models.F('project_id')),
                        ('subject_type', 'project'),
                        ('team__isnull', True),
                        ('work_type', 'weekly_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('subject_id', models.F('team_id')),
                        ('subject_type', 'team'),
                        ('team__isnull', False),
                        ('work_type', 'weekly_digest'),
                        models.Q(('occurrence_key', ''), _negated=True),
                    ),
                    models.Q(
                        ('occurrence_key', ''),
                        ('subject_type', 'memory_candidate'),
                        ('work_type', 'candidate_decision'),
                    ),
                    models.Q(
                        ('occurrence_key', ''),
                        ('subject_type', 'retrieval_document'),
                        ('work_type', 'memory_embedding'),
                    ),
                    _connector='OR',
                ),
                name='core_work_subject_scope_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='workflowwork',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('disposition', 'required'), ('resolution_reason', ''), ('resolved_at__isnull', True)),
                    models.Q(
                        ('disposition', 'complete'),
                        ('resolution_reason__in', ('succeeded', 'no_signal', 'projection_superseded')),
                        ('resolved_at__isnull', False),
                    ),
                    models.Q(
                        ('disposition', 'no_op'), ('resolution_reason', 'no_input'), ('resolved_at__isnull', False)
                    ),
                    _connector='OR',
                ),
                name='core_work_terminal_state_ck',
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='candidate',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_conflicts', to='core.memorycandidate'
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='memory',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_conflicts', to='core.memory'
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='memory_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_conflicts', to='core.memoryversion'
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_conflicts', to='core.organization'
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_conflicts', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='semantic_link',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_conflict', to='core.memorylink'
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_conflicts',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='audit_event',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_transition', to='core.auditevent'
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='candidate',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_transitions',
                to='core.memorycandidate',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='embedding_work',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='embedding_transition',
                to='core.workflowwork',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='exact_document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_transitions',
                to='core.retrievaldocument',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='from_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='outgoing_memory_transitions',
                to='core.memoryversion',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='memory',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_transitions', to='core.memory'
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_transitions', to='core.organization'
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_transitions', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='result_exact_document',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='result_memory_transitions',
                to='core.retrievaldocument',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='result_memory',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='result_memory_transitions', to='core.memory'
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='result_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='result_memory_transitions',
                to='core.memoryversion',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='semantic_link',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_transition',
                to='core.memorylink',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_transitions',
                to='core.team',
            ),
        ),
        migrations.AddField(
            model_name='memorytransition',
            name='to_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='incoming_memory_transitions',
                to='core.memoryversion',
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='opened_transition',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='opened_memory_conflict',
                to='core.memorytransition',
            ),
        ),
        migrations.AddField(
            model_name='memoryconflict',
            name='resolved_transition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='resolved_memory_conflicts',
                to='core.memorytransition',
            ),
        ),
        migrations.AddField(
            model_name='memory',
            name='current_transition',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='current_memories',
                to='core.memorytransition',
            ),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(
                fields=['organization', 'project', 'transition_contract_version'], name='core_memory_transition_ver_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='memory',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('current_transition__isnull', True), ('transition_contract_version', 0)),
                    models.Q(('current_transition__isnull', False), ('transition_contract_version', 1)),
                    _connector='OR',
                ),
                name='core_memory_transition_pointer_ck',
            ),
        ),
        migrations.AddField(
            model_name='memoryversionsource',
            name='candidate_source',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_version_sources',
                to='core.memorycandidatesource',
            ),
        ),
        migrations.AddField(
            model_name='memoryversionsource',
            name='memory_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='provenance_sources', to='core.memoryversion'
            ),
        ),
        migrations.AddField(
            model_name='memoryversionsource',
            name='organization',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_version_sources',
                to='core.organization',
            ),
        ),
        migrations.AddField(
            model_name='memoryversionsource',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='memory_version_sources', to='core.project'
            ),
        ),
        migrations.AddField(
            model_name='memoryversionsource',
            name='source_memory_version',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='derived_provenance_sources',
                to='core.memoryversion',
            ),
        ),
        migrations.AddField(
            model_name='memoryversionsource',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='memory_version_sources',
                to='core.team',
            ),
        ),
        migrations.AddIndex(
            model_name='memorytransition',
            index=models.Index(fields=['organization', 'project', 'created_at'], name='core_memtrans_scope_time_idx'),
        ),
        migrations.AddIndex(
            model_name='memorytransition',
            index=models.Index(
                fields=['organization', 'project', 'transition_type', 'created_at'], name='core_mtrans_scope_type_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='memorytransition',
            index=models.Index(fields=['candidate'], name='core_memtrans_candidate_idx'),
        ),
        migrations.AddIndex(
            model_name='memorytransition',
            index=models.Index(fields=['memory'], name='core_memtrans_memory_idx'),
        ),
        migrations.AddIndex(
            model_name='memorytransition',
            index=models.Index(fields=['result_memory'], name='core_mtrans_result_mem_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorytransition',
            constraint=models.UniqueConstraint(
                fields=('organization', 'project', 'idempotency_key'), name='core_memory_transition_idempotency_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='memorytransition',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('candidate__isnull', False), ('transition_type__in', ('promote', 'conflict_resolve'))
                ),
                fields=('candidate',),
                name='core_memory_transition_candidate_terminal_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='memorytransition',
            constraint=models.CheckConstraint(
                condition=models.Q(('request_fingerprint__regex', '^[0-9a-f]{64}$')),
                name='core_memory_transition_request_fingerprint_hex',
            ),
        ),
        migrations.AddConstraint(
            model_name='memorytransition',
            constraint=models.CheckConstraint(
                condition=models.Q(('provenance_hash__regex', '^[0-9a-f]{64}$')),
                name='core_memory_transition_provenance_hash_hex',
            ),
        ),
        migrations.AddConstraint(
            model_name='memorytransition',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('transition_type__in', ('promote', 'attach_source', 'conflict_open', 'conflict_resolve')),
                        _negated=True,
                    ),
                    ('candidate__isnull', False),
                    _connector='OR',
                ),
                name='core_memory_transition_candidate_required_ck',
            ),
        ),
        migrations.AddIndex(
            model_name='memoryconflict',
            index=models.Index(fields=['organization', 'project', 'created_at'], name='core_memconf_scope_time_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryconflict',
            index=models.Index(fields=['candidate'], name='core_memconf_candidate_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryconflict',
            index=models.Index(fields=['memory'], name='core_memconf_memory_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryconflict',
            constraint=models.UniqueConstraint(
                fields=('candidate', 'memory'), name='core_memory_conflict_candidate_memory_uniq'
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryconflict',
            constraint=models.CheckConstraint(
                condition=models.Q(('evidence_hash__regex', '^[0-9a-f]{64}$')),
                name='core_memory_conflict_evidence_hash_hex',
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryconflict',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('resolution', ''), ('resolved_at__isnull', True), ('resolved_transition__isnull', True)),
                    models.Q(
                        (
                            'resolution__in',
                            ['publish_candidate', 'merge_candidate', 'supersede_memory', 'reject_candidate'],
                        ),
                        ('resolved_at__isnull', False),
                        ('resolved_transition__isnull', False),
                    ),
                    _connector='OR',
                ),
                name='core_memory_conflict_open_close_ck',
            ),
        ),
        migrations.AddIndex(
            model_name='memoryversionsource',
            index=models.Index(
                fields=['organization', 'project', 'memory_version'], name='core_memversource_scope_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryversionsource',
            constraint=models.UniqueConstraint(
                condition=models.Q(('candidate_source__isnull', False)),
                fields=('memory_version', 'candidate_source'),
                name='core_memory_version_source_candidate_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryversionsource',
            constraint=models.UniqueConstraint(
                condition=models.Q(('source_memory_version__isnull', False)),
                fields=('memory_version', 'source_memory_version'),
                name='core_memory_version_source_memory_uniq',
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryversionsource',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('candidate_source__isnull', False), ('source_memory_version__isnull', True)),
                    models.Q(('candidate_source__isnull', True), ('source_memory_version__isnull', False)),
                    _connector='OR',
                ),
                name='core_memory_version_source_exactly_one_fk_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryversionsource',
            constraint=models.CheckConstraint(
                condition=models.Q(('memory_version_id', models.F('source_memory_version_id')), _negated=True),
                name='core_memory_version_source_no_self_reference_ck',
            ),
        ),
        migrations.AddConstraint(
            model_name='memoryversionsource',
            constraint=models.CheckConstraint(
                condition=models.Q(('source_content_hash__regex', '^[0-9a-f]{64}$')),
                name='core_memory_version_source_hash_hex',
            ),
        ),
        migrations.RunPython(_allow_forward, _guard_reverse),
    ]
