# Generated by Django 5.2.16 on 2026-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_curation_decision'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'project', 'target_type', 'target_id', 'created_at'], name='core_audit_target_idx'),
        ),
    ]
