# Generated by Django 5.2.16 on 2026-07-21 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0041_auditevent_target_index'),
        ('core', '0045_agent_proposal_source'),
    ]

    operations = []
