# Generated by Django 5.2.16 on 2026-07-22 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0047_distill_stage_coord_prompt_contract'),
        ('model_policy', '0004_alter_providercallrecord_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='distillationstage',
            name='reuse_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='distillationstage',
            name='reused_from',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='reuse_children',
                to='core.distillationstage',
            ),
        ),
        migrations.AlterField(
            model_name='distillationstage',
            name='accepted_provider_call',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accepted_distillation_stages',
                to='model_policy.providercallrecord',
            ),
        ),
        migrations.AddIndex(
            model_name='distillationstage',
            index=models.Index(
                fields=['organization', 'project', 'reuse_key', 'status'], name='core_distill_stage_reuse_idx'
            ),
        ),
    ]
