# Generated by Django 5.2.16 on 2026-07-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0048_distillation_stage_extract_reuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorycandidate',
            name='decision_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memorycandidate',
            name='decision_embedding_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=128),
        ),
    ]
