# Generated by Django 5.2.15 on 2026-06-25 20:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0003_delete_outboxevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'scope',
                    models.CharField(
                        choices=[('organization', 'Organization'), ('team', 'Team'), ('project', 'Project')],
                        max_length=40,
                    ),
                ),
                (
                    'task_type',
                    models.CharField(
                        choices=[
                            ('generation', 'Generation'),
                            ('embedding', 'Embedding'),
                            ('curation', 'Curation'),
                            ('digest', 'Digest'),
                            ('rerank', 'Rerank'),
                            ('admin_assistant', 'Admin Assistant'),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    'provider',
                    models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI')], max_length=40),
                ),
                ('model', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('allowed_providers', models.JSONField(blank=True, default=list)),
                ('blocked_providers', models.JSONField(blank=True, default=list)),
                ('fallback_enabled', models.BooleanField(default=False)),
                ('retention_policy', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='model_policies',
                        to='core.organization',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='model_policies',
                        to='core.project',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='model_policies',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'scope', 'task_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                (
                    'provider',
                    models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI')], max_length=40),
                ),
                (
                    'scope',
                    models.CharField(choices=[('organization', 'Organization'), ('team', 'Team')], max_length=40),
                ),
                (
                    'storage_mode',
                    models.CharField(
                        choices=[('database_envelope', 'Database Envelope'), ('external_vault', 'External Vault')],
                        default='database_envelope',
                        max_length=40,
                    ),
                ),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('rotation_state', models.CharField(default='active', max_length=40)),
                ('secret_fingerprint', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_secrets',
                        to='core.organization',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='provider_secrets',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'team_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCallRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'provider',
                    models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI')], max_length=40),
                ),
                ('model', models.CharField(max_length=120)),
                (
                    'task_type',
                    models.CharField(
                        choices=[
                            ('generation', 'Generation'),
                            ('embedding', 'Embedding'),
                            ('curation', 'Curation'),
                            ('digest', 'Digest'),
                            ('rerank', 'Rerank'),
                            ('admin_assistant', 'Admin Assistant'),
                        ],
                        max_length=40,
                    ),
                ),
                ('policy_version', models.PositiveIntegerField()),
                ('request_id', models.CharField(max_length=255)),
                ('trace_id', models.CharField(blank=True, max_length=255)),
                ('redaction_state', models.CharField(max_length=40)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_metadata', models.JSONField(blank=True, default=dict)),
                (
                    'result',
                    models.CharField(
                        choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('recorded', 'Recorded')],
                        default='recorded',
                        max_length=40,
                    ),
                ),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_call_records',
                        to='core.organization',
                    ),
                ),
                (
                    'policy',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='provider_call_records',
                        to='model_policy.modelpolicy',
                    ),
                ),
                (
                    'project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_call_records',
                        to='core.project',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='provider_call_records',
                        to='core.team',
                    ),
                ),
                (
                    'secret',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='provider_call_records',
                        to='model_policy.providersecret',
                    ),
                ),
            ],
            options={
                'ordering': ['organization_id', 'project_id', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='modelpolicy',
            name='secret',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='model_policies',
                to='model_policy.providersecret',
            ),
        ),
        migrations.CreateModel(
            name='ProviderSecretEnvelope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('key_version', models.CharField(max_length=40)),
                ('ciphertext', models.TextField()),
                ('hmac_digest', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='provider_secret_envelopes',
                        to='core.organization',
                    ),
                ),
                (
                    'secret',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='envelopes',
                        to='model_policy.providersecret',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='provider_secret_envelopes',
                        to='core.team',
                    ),
                ),
            ],
            options={
                'ordering': ['secret_id', 'version'],
            },
        ),
        migrations.AddIndex(
            model_name='providersecret',
            index=models.Index(fields=['organization', 'provider', 'active'], name='model_polic_organiz_7a5584_idx'),
        ),
        migrations.AddIndex(
            model_name='providersecret',
            index=models.Index(fields=['organization', 'team', 'provider'], name='model_polic_organiz_226770_idx'),
        ),
        migrations.AddIndex(
            model_name='providercallrecord',
            index=models.Index(fields=['organization', 'project', 'task_type'], name='model_polic_organiz_26a8c7_idx'),
        ),
        migrations.AddIndex(
            model_name='providercallrecord',
            index=models.Index(fields=['organization', 'provider', 'model'], name='model_polic_organiz_3b5a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='modelpolicy',
            index=models.Index(
                fields=['organization', 'project', 'task_type', 'active'], name='model_polic_organiz_a10b95_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='modelpolicy',
            index=models.Index(
                fields=['organization', 'team', 'task_type', 'active'], name='model_polic_organiz_5ef442_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='modelpolicy',
            index=models.Index(fields=['organization', 'scope', 'task_type'], name='model_polic_organiz_1c399e_idx'),
        ),
        migrations.AddIndex(
            model_name='providersecretenvelope',
            index=models.Index(fields=['organization', 'secret', 'active'], name='model_polic_organiz_166e52_idx'),
        ),
        migrations.AddConstraint(
            model_name='providersecretenvelope',
            constraint=models.UniqueConstraint(
                fields=('secret', 'version'), name='model_policy_secret_envelope_unique_version'
            ),
        ),
    ]
