# Generated by Django 5.2.15 on 2026-06-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpolicy',
            name='provider',
            field=models.CharField(
                choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], max_length=40
            ),
        ),
        migrations.AlterField(
            model_name='providercallrecord',
            name='provider',
            field=models.CharField(
                choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], max_length=40
            ),
        ),
        migrations.AlterField(
            model_name='providersecret',
            name='provider',
            field=models.CharField(
                choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek')], max_length=40
            ),
        ),
    ]
