# Generated by Django 5.2.15 on 2026-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_agentsession_model_id'),
        ('model_policy', '0002_alter_modelpolicy_provider_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='providercallrecord',
            index=models.Index(
                fields=['organization', 'project', 'task_type', 'request_id'],
                name='model_polic_organiz_6a2f50_idx',
            ),
        ),
    ]
