from __future__ import annotations

import argparse
import hashlib
import json
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

EMBEDDING_DIMENSION = 1536
GENERATION_TITLE_PREFIX = 'E2E memory'
DIGEST_TITLE_PREFIX = 'E2E digest'


def deterministic_embedding(text: str) -> list[float]:
    vector = [0.0] * EMBEDDING_DIMENSION
    for token in text.split():
        digest = hashlib.sha256(token.encode()).digest()
        index = int.from_bytes(digest[:8], 'big') % EMBEDDING_DIMENSION
        vector[index] += 1.0
    norm = sum(component**2 for component in vector) ** 0.5
    if norm == 0.0:
        vector[0] = 1.0

        return vector

    return [component / norm for component in vector]


SESSION_TITLE_PREFIX = 'E2E session memory'


def generation_content(system_prompt: str, prompt: str) -> str:
    digest_suffix = hashlib.sha256(prompt.encode()).hexdigest()[:10]
    if 'session distillation engine' in system_prompt:
        return json.dumps(
            {
                'memories': [
                    {
                        'title': f'{SESSION_TITLE_PREFIX} {digest_suffix}',
                        'body': f'Fixed session-distilled memory produced by the mock provider for {digest_suffix}.',
                        'confidence': 0.9,
                        'supporting_observation_ids': [],
                    },
                ],
            },
        )
    if 'synthesis engine' in system_prompt or 'digest' in system_prompt.lower():
        return f'{DIGEST_TITLE_PREFIX} {digest_suffix}\nFixed digest body generated by the mock provider for {digest_suffix}.'

    return (
        f'{GENERATION_TITLE_PREFIX} {digest_suffix}\n'
        f'Fixed durable engineering memory produced by the mock provider for {digest_suffix}.'
    )


class MockState:
    def __init__(
        self,
        scenario: list[dict[str, object]],
        api_key: str,
        log_path: Path,
        provider_key: str = '',
    ) -> None:
        self.scenario = scenario
        self.api_key = api_key
        self.provider_key = provider_key
        self.log_path = log_path
        self.lock = threading.Lock()
        self.turn_index = 0

    def next_turn(self) -> dict[str, object]:
        with self.lock:
            if self.turn_index < len(self.scenario):
                turn = self.scenario[self.turn_index]
                self.turn_index += 1

                return turn

            return {'text': 'ok'}

    def log_request(self, record: dict[str, object]) -> None:
        with self.lock:
            with self.log_path.open('a', encoding='utf-8') as handle:
                handle.write(json.dumps(record, ensure_ascii=False) + '\n')


def build_content_blocks(turn: dict[str, object]) -> tuple[list[dict[str, object]], str]:
    tool_uses = turn.get('tool_uses')
    if isinstance(tool_uses, list) and tool_uses:
        blocks = []
        for index, tool_use in enumerate(tool_uses):
            blocks.append(
                {
                    'type': 'tool_use',
                    'id': f'toolu_mock_{int(time.time() * 1000)}_{index}',
                    'name': str(tool_use['name']),
                    'input': tool_use.get('input') or {},
                },
            )

        return blocks, 'tool_use'

    return [{'type': 'text', 'text': str(turn.get('text') or 'ok')}], 'end_turn'


def message_payload(model: str, blocks: list[dict[str, object]], stop_reason: str) -> dict[str, object]:
    return {
        'id': f'msg_mock_{int(time.time() * 1000)}',
        'type': 'message',
        'role': 'assistant',
        'model': model,
        'content': blocks,
        'stop_reason': stop_reason,
        'stop_sequence': None,
        'usage': {'input_tokens': 100, 'output_tokens': 50},
    }


def sse_events(model: str, blocks: list[dict[str, object]], stop_reason: str) -> list[tuple[str, dict[str, object]]]:
    start_message = message_payload(model, [], None)  # type: ignore[arg-type]
    start_message['stop_reason'] = None
    events: list[tuple[str, dict[str, object]]] = [
        ('message_start', {'type': 'message_start', 'message': start_message}),
    ]
    for index, block in enumerate(blocks):
        if block['type'] == 'tool_use':
            events.append(
                (
                    'content_block_start',
                    {
                        'type': 'content_block_start',
                        'index': index,
                        'content_block': {
                            'type': 'tool_use',
                            'id': block['id'],
                            'name': block['name'],
                            'input': {},
                        },
                    },
                ),
            )
            events.append(
                (
                    'content_block_delta',
                    {
                        'type': 'content_block_delta',
                        'index': index,
                        'delta': {
                            'type': 'input_json_delta',
                            'partial_json': json.dumps(block['input'], ensure_ascii=False),
                        },
                    },
                ),
            )
        else:
            events.append(
                (
                    'content_block_start',
                    {
                        'type': 'content_block_start',
                        'index': index,
                        'content_block': {'type': 'text', 'text': ''},
                    },
                ),
            )
            events.append(
                (
                    'content_block_delta',
                    {
                        'type': 'content_block_delta',
                        'index': index,
                        'delta': {'type': 'text_delta', 'text': block['text']},
                    },
                ),
            )
        events.append(('content_block_stop', {'type': 'content_block_stop', 'index': index}))
    events.append(
        (
            'message_delta',
            {
                'type': 'message_delta',
                'delta': {'stop_reason': stop_reason, 'stop_sequence': None},
                'usage': {'output_tokens': 50},
            },
        ),
    )
    events.append(('message_stop', {'type': 'message_stop'}))

    return events


class MockAnthropicHandler(BaseHTTPRequestHandler):
    state: MockState

    def log_message(self, *_args: object) -> None:
        return

    def _write_json(self, status: int, payload: dict[str, object]) -> None:
        body = json.dumps(payload).encode()
        self.send_response(status)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:
        if self.path == '/health':
            self._write_json(200, {'status': 'ok'})

            return

        self._write_json(404, {'error': {'type': 'not_found_error', 'message': self.path}})

    def _handle_openai(self, provided_key: str, request_body: dict[str, object]) -> None:
        expected = self.state.provider_key
        if not expected or expected not in provided_key:
            self._write_json(
                401,
                {'error': {'type': 'authentication_error', 'message': 'invalid provider key'}},
            )

            return

        model = str(request_body.get('model') or 'mock-model')
        if self.path.endswith('/embeddings'):
            embedding = deterministic_embedding(str(request_body.get('input') or ''))
            self._write_json(
                200,
                {
                    'object': 'list',
                    'model': model,
                    'data': [{'object': 'embedding', 'index': 0, 'embedding': embedding}],
                    'usage': {'prompt_tokens': 10, 'total_tokens': 10},
                },
            )

            return

        messages = request_body.get('messages')
        system_prompt = ''
        prompt = ''
        if isinstance(messages, list):
            for message in messages:
                if not isinstance(message, dict):
                    continue
                if message.get('role') == 'system':
                    system_prompt = str(message.get('content') or '')
                if message.get('role') == 'user':
                    prompt = str(message.get('content') or '')
        content = generation_content(system_prompt, prompt)
        self._write_json(
            200,
            {
                'id': f'chatcmpl_mock_{int(time.time() * 1000)}',
                'object': 'chat.completion',
                'model': model,
                'choices': [
                    {
                        'index': 0,
                        'message': {'role': 'assistant', 'content': content},
                        'finish_reason': 'stop',
                    },
                ],
                'usage': {'prompt_tokens': 100, 'completion_tokens': 50, 'total_tokens': 150},
            },
        )

    def do_POST(self) -> None:
        length = int(self.headers.get('Content-Length') or 0)
        raw_body = self.rfile.read(length).decode('utf-8', errors='replace') if length else ''
        try:
            request_body = json.loads(raw_body) if raw_body else {}
        except json.JSONDecodeError:
            request_body = {'unparsed': raw_body[:2000]}
        provided_key = self.headers.get('x-api-key') or self.headers.get('Authorization') or ''
        self.state.log_request(
            {
                'path': self.path,
                'api_key': provided_key,
                'model': request_body.get('model'),
                'stream': request_body.get('stream'),
                'body': request_body,
            },
        )
        if self.path.endswith('/embeddings') or self.path.endswith('/chat/completions'):
            self._handle_openai(provided_key, request_body)

            return

        if self.state.api_key not in provided_key:
            self._write_json(
                401,
                {'error': {'type': 'authentication_error', 'message': 'invalid api key'}},
            )

            return

        if self.path.endswith('/count_tokens'):
            self._write_json(200, {'input_tokens': 100})

            return

        if '/v1/messages' not in self.path:
            self._write_json(404, {'error': {'type': 'not_found_error', 'message': self.path}})

            return

        model = str(request_body.get('model') or 'claude-mock')
        if 'haiku' in model:
            blocks, stop_reason = [{'type': 'text', 'text': 'ok'}], 'end_turn'
        else:
            turn = self.state.next_turn()
            blocks, stop_reason = build_content_blocks(turn)
        if request_body.get('stream'):
            self.send_response(200)
            self.send_header('Content-Type', 'text/event-stream')
            self.send_header('Cache-Control', 'no-cache')
            self.end_headers()
            for event_name, event_payload in sse_events(model, blocks, stop_reason):
                chunk = f'event: {event_name}\ndata: {json.dumps(event_payload, ensure_ascii=False)}\n\n'
                self.wfile.write(chunk.encode())
                self.wfile.flush()

            return

        self._write_json(200, message_payload(model, blocks, stop_reason))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--port', type=int, required=True)
    parser.add_argument('--api-key', required=True)
    parser.add_argument('--scenario', required=True)
    parser.add_argument('--log', required=True)
    parser.add_argument('--provider-key', default='')
    parser.add_argument('--bind', default='127.0.0.1')
    args = parser.parse_args()

    scenario = json.loads(Path(args.scenario).read_text(encoding='utf-8'))
    if not isinstance(scenario, list):
        raise SystemExit('scenario must be a JSON list of turns')

    log_path = Path(args.log)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    handler = MockAnthropicHandler
    handler.state = MockState(scenario, args.api_key, log_path, provider_key=args.provider_key)
    server = ThreadingHTTPServer((args.bind, args.port), handler)
    print(f'[mock-anthropic] listening on {args.bind}:{args.port}', flush=True)
    server.serve_forever()

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
